### ISSUE TITLE
coloraction: output as hexstring and hex8string

### ISSUE THREAD

**Issue by kookma** [rimi/tw5-telmiger-plugins#6]
I am using coloraction for [Color Play]( https://colorplay.tiddlyhost.com/)

I need to always get the output as hex or hex8 string but some actions like mix does not allow me to do so?
Also I can not get the hex8 i.e. the hex + alpha value

I appreciate to have a look

**Comment by rimi** [comment]
Hi, this is just a mirror of https://tid.li/tw5/plugins.html... please send your question to Thomas, thanks!

**Comment by kookma** [comment]
Thank you!
